FROM eclipse-temurin:17-jdk AS build
WORKDIR /app
COPY . .
RUN ./gradlew :rest:bootJar --no-daemon

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/rest/build/libs/*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]
